Update the user support page
alphagov/gds-way pull request #896
Opened 2024-05-03 15:19 UTC by louzoid-gds

Brought the content more up to date and rearranged it slightly

2024-05-09 09:20 UTC, timblair requested changes
LGTM, other than fixing this link and adding a full stop.

2024-05-09 09:20 UTC, timblair commented on source/standards/user-support.html.md.erb
> +2nd line support provide direct incident resolution (see [incident management]((incident-management.html))) and triage user requests. For example, when users receive timeout errors or performance iss
```suggestion
2nd line support provide direct incident resolution (see [incident management](/incident-management.html)) and triage user requests. For example, when users receive timeout errors or performance issues.
```

2024-05-09 09:20 UTC, timblair commented on source/standards/user-support.html.md.erb
> +However the support model varies, teams will have multiple 'lines' of support
```suggestion
However the support model varies, teams will have multiple 'lines' of support.
```

2024-05-14 15:36 UTC, louzoid-gds commented
Thanks Tim! Once the user support folks have got back to me, I'll move this PR out of draft.

2024-07-09 07:49 UTC, timblair approved these changes

2024-07-09 08:06 UTC, merged