BAU: Breaking down work
alphagov/gds-way pull request #947
Opened 2024-10-10 15:36 UTC by mrwilson

This is a cut down version of the longer blogpost: https://blog.probablyfine.co.uk/2024/09/27/why-breaking-down-work-is-important.html

2024-10-11 13:50 UTC, mrwilson commented on source/standards/breaking-down-work.html.md.erb
> +- It enables fast feedback. We can learn a lot from regularly releasing our code to production environments even if the effects are not visible to users. We also get feedback on our code design becau
I've added more to the "get work live quickly" section in the How block

2024-10-14 11:36 UTC, sarahseewhy requested changes
Only a typo to change, the other suggestion you can freely ignore.

2024-10-14 11:36 UTC, sarahseewhy commented on source/standards/breaking-down-work.html.md.erb
> +- Loosely coupled components and systems. Systems that need to be changed together will block eachother, so try to build systems that have well-defined contracts but also operate under the robustness
I think we can change "eachother" to "each other". 

Google says the correct spelling is two words instead of one.

2024-10-14 11:36 UTC, sarahseewhy commented on source/standards/breaking-down-work.html.md.erb
> +- It boosts team morale. The unit of delivery is the team, and delivering value regularly is much better than working on big-bang releases for months at a time.
Pedantic suggestion you can ignore if you would like.

The "what is better" is implied by the previous sentence, however I'd be curious to see how it reads if we change it to this:

"The unit of delivery is the team, and delivering value regularly is much better **for morale** than working on big-bang releases for months at a time"

2024-10-16 07:58 UTC, louzoid-gds reviewed
Looking great.

Two additional points to consider:

- Where are you linking to this page from? I'd suggest adding to the 'Software development' section of The GDS Way
- I think it would be useful to cross-link to this page from the Continuous Delivery page

Thanks so much mrwilson!

2024-10-16 07:58 UTC, louzoid-gds commented on source/standards/breaking-down-work.html.md.erb
> +- Loosely coupled components and systems. Systems that need to be changed together will block eachother, so try to build systems that have well-defined contracts but also operate under the robustness
> be conservative in what you send, liberal in what you send

Should this be something like 'be conservative in what you send, liberal in what you accept'?

2024-10-16 07:58 UTC, louzoid-gds commented on source/standards/breaking-down-work.html.md.erb
> +- Failing early and safely. Working in small batches reduces risk of bugs, but when those bugs to happen it's much easier to roll back a small change than a large one. Your team should be aspiring to
> but when those bugs to happen

but where those bugs do happen?

2024-10-16 10:51 UTC, mrwilson commented
I have folded in your suggestions @sarahseewhy @louzoid-gds - the post is linked from the side nav next to pair programming, and also within the continuous delivery content as a one-liner with the link.

2024-10-16 18:48 UTC, cjfryer approved these changes

2024-10-17 14:40 UTC, sarahseewhy approved these changes
Thank you! Looks grand 🪄

2024-10-18 09:16 UTC, merged