Update to the Secret Auditing page
alphagov/gds-way pull request #954
Opened 2024-10-31 11:48 UTC by minglis

As per discussion in GDS Lead Tech meeting - action was to review the guidance on GitHub secret scanning with security colleagues. 

Proposal is to upgrade the use of GitHub secret scanning to a must from should. 

This change also recommends that teams must review alerts on a regular basis, timing of this suggested to be aligned to existing team processes.

Teams also must record outcomes, even for false positives.

2024-11-07 09:48 UTC, willp-bl approved these changes

2024-11-27 10:39 UTC, huwd approved these changes
I agree with this DI are making similar moves right now.

2024-11-27 11:03 UTC, timblair requested changes
We discussed this in the GDS Way meeting, and are :+1: with it. Please can you update the review date before you merge this?

2025-02-18 14:12 UTC, timblair requested changes
Just one additional bump to the review date, otherwise 👍

2025-02-19 09:38 UTC, timblair approved these changes

2025-02-19 10:58 UTC, merged